# Simple Duplicate File Scanner
# Test version with basic functionality

param(
    [switch]$Test,
    [switch]$Help
)

Write-Host "=== OpenClaw Duplicate File Scanner (Simple) ===" -ForegroundColor Cyan
Write-Host "Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Gray
Write-Host ""

if ($Help) {
    Write-Host "Usage: .\scan-duplicates-simple.ps1 [-Test] [-Help]" -ForegroundColor Yellow
    exit 0
}

# Configuration
$config = @{
    ScanDirectories = @(
        "C:\Users\luchaochao\.openclaw\workspace",
        "C:\Users\luchaochao\Downloads"
    )
    FileTypes = @("*.txt", "*.log", "*.json", "*.md", "*.ps1", "*.bat")
    MinFileSizeKB = 1
    MaxFileSizeMB = 10
    CompareMethod = "SizeOnly"  # Simple size comparison for test
}

Write-Host "Configuration:" -ForegroundColor Yellow
Write-Host "  Directories: $($config.ScanDirectories.Count)" -ForegroundColor Gray
Write-Host "  File types: $($config.FileTypes.Count)" -ForegroundColor Gray
Write-Host "  Test mode: $Test" -ForegroundColor Gray
Write-Host ""

# Scan for files
$allFiles = @()
foreach ($dir in $config.ScanDirectories) {
    if (Test-Path $dir) {
        Write-Host "Scanning: $dir" -ForegroundColor Cyan
        
        foreach ($fileType in $config.FileTypes) {
            try {
                $files = Get-ChildItem -Path $dir -Recurse -Include $fileType -ErrorAction SilentlyContinue | 
                    Where-Object { 
                        $sizeKB = $_.Length / 1KB
                        $sizeMB = $_.Length / 1MB
                        $sizeKB -ge $config.MinFileSizeKB -and 
                        $sizeMB -le $config.MaxFileSizeMB
                    }
                
                $allFiles += $files
                Write-Host "  Found $($files.Count) $fileType files" -ForegroundColor Gray
                
                # Limit for test
                if ($Test -and $allFiles.Count -gt 50) {
                    Write-Host "  Test mode: Limiting to 50 files" -ForegroundColor Yellow
                    $allFiles = $allFiles | Select-Object -First 50
                    break
                }
            } catch {
                Write-Host "  Error: $_" -ForegroundColor Red
            }
        }
    } else {
        Write-Host "Directory not found: $dir" -ForegroundColor Yellow
    }
}

Write-Host "`nTotal files found: $($allFiles.Count)" -ForegroundColor Green

if ($allFiles.Count -eq 0) {
    Write-Host "No files to scan" -ForegroundColor Yellow
    exit 0
}

# Find duplicates by size
Write-Host "`nFinding duplicates by file size..." -ForegroundColor Yellow

$sizeGroups = $allFiles | Group-Object Length | Where-Object Count -gt 1
$duplicates = @()

foreach ($group in $sizeGroups) {
    if ($group.Count -gt 1) {
        $duplicateGroup = @{
            SizeBytes = $group.Name
            SizeMB = [math]::Round([int64]$group.Name / 1MB, 2)
            Count = $group.Count
            Files = $group.Group.FullName
            WastedMB = [math]::Round([int64]$group.Name * ($group.Count - 1) / 1MB, 2)
        }
        $duplicates += $duplicateGroup
    }
}

Write-Host "Found $($duplicates.Count) duplicate groups" -ForegroundColor Green

# Generate report
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$reportDir = "modules/duplicate/reports"
if (-not (Test-Path $reportDir)) {
    New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
}

# Simple text report
$reportFile = "$reportDir\scan-report-$timestamp.txt"

$report = @"
OpenClaw Duplicate File Scan Report
====================================
Scan Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
Test Mode: $Test

Configuration:
- Directories scanned: $($config.ScanDirectories.Count)
- File types: $($config.FileTypes -join ', ')
- Compare method: $($config.CompareMethod)

Scan Results:
- Total files scanned: $($allFiles.Count)
- Duplicate groups found: $($duplicates.Count)
- Total duplicate files: $(($duplicates | Measure-Object -Property Count -Sum).Sum)
- Space wasted: $(($duplicates | Measure-Object -Property WastedMB -Sum).Sum) MB

Duplicate Groups:
"@

foreach ($group in $duplicates) {
    $report += "`n`nGroup (Size: $($group.SizeMB) MB, Files: $($group.Count), Waste: $($group.WastedMB) MB):`n"
    foreach ($file in $group.Files) {
        $fileName = Split-Path $file -Leaf
        $report += "  - $fileName`n    $file`n"
    }
}

$report += @"

Recommendations:
1. Review duplicate files above
2. Run cleanup script: .\clean-duplicates.ps1 -Preview
3. Backup important files before cleanup
4. Execute cleanup: .\clean-duplicates.ps1

---
Report generated by OpenClaw Duplicate File Scanner v1.0.0
"@

$report | Out-File $reportFile -Encoding UTF8
Write-Host "Report saved: $reportFile" -ForegroundColor Green

# Summary
Write-Host "`n=== Scan Summary ===" -ForegroundColor Cyan
Write-Host "Files scanned: $($allFiles.Count)" -ForegroundColor Gray
Write-Host "Duplicate groups: $($duplicates.Count)" -ForegroundColor Gray
Write-Host "Duplicate files: $(($duplicates | Measure-Object -Property Count -Sum).Sum)" -ForegroundColor Gray
Write-Host "Space wasted: $(($duplicates | Measure-Object -Property WastedMB -Sum).Sum) MB" -ForegroundColor Gray
Write-Host ""
Write-Host "Report: $reportFile" -ForegroundColor Yellow
Write-Host ""
Write-Host "Next: Create clean-duplicates.ps1 script" -ForegroundColor Green
